project_id = "bjgajwvfequzvuhktrzm"

[functions.telegram-webhook]
verify_jwt = false

[functions.send-telegram-message]
verify_jwt = false

[functions.setup-webhook]
verify_jwt = false

[functions.admin-telegram-webhook]
verify_jwt = false
